title: teblog
# email: teblog@gmail.com
description: teblog blog
baseurl: ""
url: "https://teblog.github.io/"
github_username:  teblog

permalink: /:slug.html

favicon: "favicon.png"
# goat_counter: "teblog" # put your GoatCounter name if you want to use GoatCounter analytics

# Build settings
# remote_theme: riggraz/no-style-please
remote_theme: ronv/sidey

theme_config:
  appearance: "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
